# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad9478f4317d762954cd7abbbf56e543daa545a5a435155ad8d117c995843166150b96133b1242a07fb56a800634b2c5be0afcb951309876a38472995c52246

test:
  secret_key_base: 4404f57ba375ec181bb23bc4ef016e2724dee8801ff46eb269acf37df908c5c8fb57473b19d2dce263c21e89ba6edb75e5d764bb5bd48ad231dbb1cb60407e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
